sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - node

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run build:lib
  - npm run docs

deploy:
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
